all: part1 partA partB partC
part1: part1.c
	gcc part1.c MyString.c -o part1
partA: partA.c
	gcc partA.c Team.c -o partA
partB: partB.c
	gcc partB.c Team.c -o partB
partC: partC.c
	gcc partC.c Team.c -o partC
clean:
	rm part1 partA partB partC 
